spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

kafka:
  bootstrap-servers: kafka:9092
